import { z, type ZodTypeAny } from 'zod';

/**
 * Simplified JSON Schema structure as generated by the form module.
 */
interface JSONSchemaProperty {
  type: string;
  enum?: string[];
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  pattern?: string;
}

interface JSONSchema {
  type: string;
  properties: Record<string, JSONSchemaProperty>;
  required?: string[];
}

/**
 * Converts a single JSON Schema property definition to a Zod validator.
 */
function propertyToZod(prop: JSONSchemaProperty, isRequired: boolean): ZodTypeAny {
  let schema: ZodTypeAny;

  switch (prop.type) {
    case 'string': {
      let strSchema = z.string();
      if (prop.minLength !== undefined) {
        strSchema = strSchema.min(prop.minLength);
      }
      if (prop.maxLength !== undefined) {
        strSchema = strSchema.max(prop.maxLength);
      }
      if (prop.pattern) {
        strSchema = strSchema.regex(new RegExp(prop.pattern));
      }
      if (prop.enum && prop.enum.length > 0) {
        schema = z.enum(prop.enum as [string, ...string[]]);
      } else {
        schema = strSchema;
      }
      break;
    }
    case 'number':
    case 'integer': {
      let numSchema = z.number();
      if (prop.type === 'integer') {
        numSchema = numSchema.int();
      }
      if (prop.minimum !== undefined) {
        numSchema = numSchema.min(prop.minimum);
      }
      if (prop.maximum !== undefined) {
        numSchema = numSchema.max(prop.maximum);
      }
      schema = numSchema;
      break;
    }
    case 'boolean':
      schema = z.boolean();
      break;
    case 'array':
      schema = z.array(z.unknown());
      break;
    default:
      schema = z.unknown();
  }

  if (!isRequired) {
    schema = schema.optional();
  }

  return schema;
}

/**
 * Converts a JSON Schema object to a Zod schema for validation.
 * Supports basic JSON Schema types: string, number, integer, boolean, array.
 */
export function jsonSchemaToZod(jsonSchema: unknown): z.ZodObject<Record<string, ZodTypeAny>> {
  const schema = jsonSchema as JSONSchema;

  if (!schema || schema.type !== 'object' || !schema.properties) {
    // If schema is not a valid object schema, accept any object
    return z.object({});
  }

  const requiredFields = new Set(schema.required ?? []);
  const shape: Record<string, ZodTypeAny> = {};

  for (const [key, prop] of Object.entries(schema.properties)) {
    shape[key] = propertyToZod(prop, requiredFields.has(key));
  }

  return z.object(shape);
}

/**
 * Validates response data against a JSON Schema.
 * Returns { valid: true } or { valid: false, errors: string[] }.
 */
export function validateResponses(
  responses: Record<string, unknown>,
  jsonSchema: unknown,
): { valid: true } | { valid: false; errors: string[] } {
  const zodSchema = jsonSchemaToZod(jsonSchema);
  const result = zodSchema.safeParse(responses);

  if (result.success) {
    return { valid: true };
  }

  const errors = result.error.issues.map(
    (issue) => `${issue.path.join('.')}: ${issue.message}`,
  );

  return { valid: false, errors };
}
